---
arch_paru_packages:
  - 1password
  - discord
  - stow
  - eza
  - starship
  - github-cli
  - ttf-meslo-nerd
  - git-delta
  - ghostty
  - zoxide
  - zellij
  - nodejs
  - npm

zellij_plugin_dir: "{{ ansible_facts.env.HOME }}/.local/share/zellij/plugins"
