---
arch_paru_packages:
  - 1password
  - discord
  - stow
  - exa
  - starship
  - github-cli
  - ttf-meslo-nerd
  - git-delta
  - ghostty
  - zoxide
  - zellij

zellij_plugin_dir: "{{ ansible_facts.env.HOME }}/.local/share/zellij/plugins"
