---
- name: Add HashiCorp repo
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: '0644'
  become: true

- name: Install dnf packages
  ansible.builtin.dnf:
    name: "{{ fedora_dnf_packages }}"
    state: present
  become: true

- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0755'

- name: Download nerd fonts
  ansible.builtin.get_url:
    url: "https://www.naurwhal.com/fonts/{{ item }}"
    dest: "{{ ansible_facts.env.HOME }}/.local/share/fonts/{{ item }}"
    mode: '0644'
  loop: "{{ nerd_fonts }}"
  notify: Refresh font cache

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: homebrew_check

- name: Create linuxbrew directory
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0755'
  become: true
  when: not homebrew_check.stat.exists

- name: Install Homebrew
  ansible.builtin.shell: |
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not homebrew_check.stat.exists

- name: Install brew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_facts.env.PATH }}"