---
- name: Ensure tmux plugins directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.tmux/plugins"
    state: directory
    mode: '0755'

- name: Clone TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts.env.HOME }}/.tmux/plugins/tpm"
    update: false
