---
- name: Update system and install packages with paru
  ansible.builtin.command:
    cmd: paru -Syu --needed --noconfirm {{ arch_paru_packages | join(' ') }}
  register: paru_result
  changed_when: "'installing' in paru_result.stdout or 'upgrading' in paru_result.stdout"
